"""fix clinic relationships_2

Revision ID: aa5201cd5abe
Revises: 27e8fc7ba689
Create Date: 2025-10-21 22:22:10.733344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa5201cd5abe'
down_revision: Union[str, None] = '27e8fc7ba689'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
