"""fix clinic relationships_3

Revision ID: c69d83fd244a
Revises: aa5201cd5abe
Create Date: 2025-10-21 22:25:15.290175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c69d83fd244a'
down_revision: Union[str, None] = 'aa5201cd5abe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
